theme: jekyll-theme-cayman
title: SBCod
description: Site-ul clubului de informatica SBCod.
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
